dbinfo:
   oracleip: 10.10.84.150
   oracleport: 1521
   oracleid: adm_vit
   oraclepw: "vit_adm123!"
   oracledatabasename: vitdb
   mongouri:  mongodb://pcsadm:pcsadm%2100@10.11.63.112:27017,10.11.63.113:27017,10.11.63.114:27017/
   mongodatabasename: ApptxPersonalization
   mongodatabaseargs: replicaSet=PCSReplSet&authSource=admin
   fromRowNum: 1
   toRowNum: 10000
   infoTableFromSeq : 1
   infoTableToSeq : 10000
   servicetype: "0"
   fromUptDtm: "20121220071237"
   toUptDtm : "20121220071237"   
   bulkUpdateYn : "Y"

#spring:
#  data:
#    mongodb:
#      uri: mongodb://admin:admin@localhost:27017,localhost:27018,localhost:27019/test?authSource=admin&replicaSet=replset
#      database: test
---
logging:
  path: ./
  file: etl.log
  level:
    root: info
    sun.rmi: info
    org.mongodb: info
    org.springframework: info
    com.mongodb.migtool: debug
    com.zaxxer.hikari: off
